# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cae7a6a5012ff07dcb011c2f590b2bc9ca6a6bda31c61411b4a942eee7c488c2601d30a98824fbda1c3f3510d28079e2ff5c1167e4787412aa1e312478f7fb1

test:
  secret_key_base: 4d44a0e6ef92417cd002a37c909e3700aea43d388e795a3802d850930fc9c604d8f16fd1f3150947d1a7d8c6575900ceb4025afdce1a2e23aef9919e2fe9776e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
